_format_version: '2.1'
_transform: true

services:

- name: business-api
  url: http://apiserver:3001
  routes:
  - name: business-api-route
    paths:
    - /
  plugins:
  - name: oauth-proxy
    config:
      cookie_name_prefix: example
      encryption_key: $ENCRYPTION_KEY
      trusted_web_origins:
      - http://www.example.com
      cors_enabled: true
      cors_allowed_methods:
      - 'OPTIONS'
      - 'GET'
      - 'POST'
      cors_allowed_headers:
      - 'x-example-csrf'
      cors_exposed_headers: []
      cors_max_age: 86400
