version: '3.8'
services:

  #
  # Use Kong Open Source as the reverse proxy when the kong profile is set on the command line
  #
  kong:
    image: custom_kong:3.0.0-alpine
    hostname: kongserver
    ports:
      - 3000:3000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,oauth-proxy'
    profiles:
      - kong

  #
  # Use OpenResty as the reverse proxy when the openresty profile is set on the command line
  #
  openresty:
    image: custom_openresty:1.21.4.1-bionic
    hostname: openrestyserver
    ports:
      - 3000:3000
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    environment:
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
    profiles:
      - openresty

  #
  # A tiny API as a target for testing routing
  #
  business-api:
    hostname: apiserver
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile