version: '3.8'
services:

  #
  # Use Kong Open Source as the reverse proxy when the kong profile is set on the command line
  #
  kong:
    image: kong:2.6.0-alpine
    hostname: kongserver
    ports:
      - 3000:3000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ../plugin:/usr/local/share/lua/5.1/kong/plugins/bff-token
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,bff-token'
    profiles:
      - kong

  #
  # Use OpenResty as the reverse proxy when the openresty profile is set on the command line
  #
  openresty:
    image: openresty/openresty:1.19.9.1-bionic
    hostname: openrestyserver
    ports:
      - 3000:3000
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ../plugin/access.lua:/usr/local/openresty/lualib/bff-token-plugin.lua
      - ./lua-resty-cookie/lib/resty/cookie.lua:/usr/local/openresty/lualib/resty/cookie.lua
    profiles:
      - openresty

  #
  # A tiny API as a target for testing routing
  #
  business-api:
    hostname: apiserver
    build:
      context: .
      dockerfile: ./api/Dockerfile